apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: 'true'
  labels:
    app: nodejs-mongodb-example
    template: nodejs-mongodb-example
    template.openshift.io/template-instance-owner: e6186f20-7af0-11e9-9dcf-023b1fa5415e
  name: nodejs-mongodb-example
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'nodejs-mongodb-example:latest'
  postCommit:
    script: npm test
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/sclorg/nodejs-ex.git'
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: NPM_MIRROR
      from:
        kind: ImageStreamTag
        name: 'nodejs:8'
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
    - github:
        secret: GhJ5XY6ICAErHDnDErDRIHrAr5oWdMAFRmhpBEr4
      type: GitHub
    - generic:
        secret: 0HF1JpgTyh5wr5gLKKG6tbxQb7N1tuSJ3dQWUkL1
      type: Generic
